default: &default
  adapter: postgresql
  encode: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: recipe_app
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: recipe_app

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  database:  recipe_app_production
